workflows:
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
                XCODE_WORKSPACE: "ios/react_native_ios.xcworkspace" # <-- Put the name of your Xcode workspace here
                XCODE_SCHEME: "react_native_ios" # <-- Put the name of your Xcode scheme here
            node: latest
            xcode: 12.5
            cocoapods: default
        scripts:
     
            - name: Install npm dependencies
              script: |
                npm install
            - name: Deintegrate
              script: | 
                rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData && pod deintegrate && pod install
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Build ipa for distribution
              script: |
                xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 
        artifacts:
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
